# Generated by Django 5.0.4 on 2024-04-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('Login', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('Otchestvo', models.CharField(max_length=20)),
                ('DateofBirth', models.DateField()),
                ('INN', models.IntegerField()),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='procedure.status')),
                ('FIO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.user')),
            ],
        ),
    ]
