# Generated by Django 5.0.4 on 2024-04-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_alter_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='FIO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='procedure.user'),
        ),
    ]
